performeter:
  orchestrator:
    testDurationSeconds: 60

  executor:
    corePoolSize: 20
    maxPoolSize: 40
    queueCapacity: 10

  hazlecast:
    maxNumberOfCacheElements: 1000

  redis:
    maxNumberOfCacheElements: 1000

  infinispan:
    maxNumberOfCacheElements: 1000

  geode:
    host: QQQQQQQQQ
    port: 10334
    testregion:
      type: CACHING_PROXY
      name: region
pump:
    srcDriverclass: com.tmax.tibero.jdbc.TbDriver
    srcUrl: jdbc:tibero:thin:@10.31.20.54:8629:DWH
    srcUser: frontoffice_fo
    srcPassword: q1
    srcSql: select * from FF_OL_FOR_TEST