performeter:
  orchestrator:
    testDurationSeconds: 60

  executor:
    corePoolSize: 20
    maxPoolSize: 40
    queueCapacity: 10

  hazlecast:
    maxNamberOfCacheElements: 1000

  redis:
    maxNamberOfCacheElements: 1000

  geode:
    host: QQQQQQQQQ
    port: 10334
    testregion:
      type: CACHING_PROXY
      name: region
