- name: configure the master redis server
  hosts: redis-master
  roles:
    - DavidWittman.redis

- name: configure redis slaves
  hosts: redis-slave
  vars:
    - redis_slaveof: "{{ groups['redis-master'][0] }} 6379"
  roles:
    - DavidWittman.redis

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  vars:
    - redis_sentinel: true
    - redis_sentinel_monitors:
      - name: mymaster
        host: "{{ groups['redis-master'][0] }}"
        port: 6379
  roles:
    - DavidWittman.redis

