performeter:
  orchestrator:
    testDurationSeconds: 600

  executor:
    corePoolSize: 20
    maxPoolSize: 40
    queueCapacity: 10

  hazlecast:
    maxNumberOfCacheElements: 2000

  redis:
    maxNumberOfCacheElements: 1000

  geode:
    host: QQQQQQQQQ
    port: 10334
    testregion:
      type: CACHING_PROXY
      name: region
pump:
    srcDriverClass: com.tmax.tibero.jdbc.TbDriver
    srcURL: jdbc:tibero:thin:@10.31.20.54:8629:DWH
    srcUserID: frontoffice_fo
    srcPassword: q1
    srcStatement: select env_timein,txn_f2,txn_f3,txn_f4,txn_f32,txn_f37,txn_f38,txn_f39,txn_f41,txn_f42,txn_f62_2 from FF_OL_FOR_TEST
dataProvider:
    queueCapacity: 10000
